name: Build UnityPackage

on:
  push:
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Create Global
      run: |
        mkdir -p global.json
        echo "{"sdk":{"version":"7.0.101","rollForward":"patch","allowPrerelease":false}}" > global.json

    - uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Create IntegrationManager Directory
      run: |
        mkdir -p IntegrationManager
        
        # Copy assets to IntegrationManager
        find . -maxdepth 1 -mindepth 1 -not -name "IntegrationManager" -exec cp -R {} IntegrationManager/ \;
        echo "Repository files copied to IntegrationManager."

        # Create .meta files for IntegrationManager
        touch IntegrationManager.meta
        echo "fileFormatVersion: 2" > IntegrationManager.meta
        echo "guid: e179bf41f223f1b478e0c00e9f819864" >> IntegrationManager.meta
        echo "folderAsset: yes" >> IntegrationManager.meta
        echo "DefaultImporter:" >> IntegrationManager.meta
        echo "  externalObjects: {}" >> IntegrationManager.meta
        echo "  userData:" >> IntegrationManager.meta
        echo "  assetBundleName:" >> IntegrationManager.meta
        echo "  assetBundleVariant:" >> IntegrationManager.meta
        
    - name: Create GlitchSDK Directory
      run: |
        mkdir -p GlitchSDK
        
        # Copy your assets to GlitchSDK
        cp -R IntegrationManager GlitchSDK/
        echo "Repository files copied to GlitchSDK."

        # Create .meta files for GlitchSDK
        touch GlitchSDK.meta
        echo "fileFormatVersion: 2" > GlitchSDK.meta
        echo "guid: 35413811acd778c49a42dd3a6f867699" >> GlitchSDK.meta
        echo "folderAsset: yes" >> GlitchSDK.meta
        echo "DefaultImporter:" >> GlitchSDK.meta
        echo "  externalObjects: {}" >> GlitchSDK.meta
        echo "  userData:" >> GlitchSDK.meta
        echo "  assetBundleName:" >> GlitchSDK.meta
        echo "  assetBundleVariant:" >> GlitchSDK.meta
    
    - name: build
      uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2021 }}
      with:
        projectPath: GlitchSDK
        unityVersion: 2021.3.11f1
        targetPlatform: StandaloneLinux64
        buildMethod: PackageExporter.Export
        customParameters: /headless /ScriptBackend mono
        versioning: None
    - uses: Cysharp/Actions/.github/actions/check-metas@main # check meta files
      with:
        directory: GlitchSDK
    - uses: actions/upload-artifact@v3
      with:
        name: IntegrationManager.unitypackage
        path: bin/*.unitypackage
