name: Build UnityPackage

on:
  push:
    tags:
      - '*'

jobs:
  conditional-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Read Details
      run: |
        echo "DETAILS_JSON=$(jq -c . < Details.json)" >> $GITHUB_ENV
    - run: |
        echo "Details Version: ${{ fromJson(env.DETAILS_JSON).version }}"

    - name: Create Package Directory
      run: |
        mkdir -p ${{ fromJson(env.DETAILS_JSON).name }}
        
        # Copy assets to Package
        find . -maxdepth 1 -mindepth 1 -not -name "${{ fromJson(env.DETAILS_JSON).name }}" -exec cp -R {} ${{ fromJson(env.DETAILS_JSON).name }}/ \;
        echo "Repository files copied to ${{ fromJson(env.DETAILS_JSON).name }}."

        # Create .meta files for Package
        touch ${{ fromJson(env.DETAILS_JSON).name }}.meta
        echo "fileFormatVersion: 2" > ${{ fromJson(env.DETAILS_JSON).name }}.meta
        echo "guid: e179bf41f223f1b478e0c00e9f819864" >> ${{ fromJson(env.DETAILS_JSON).name }}.meta
        echo "folderAsset: yes" >> ${{ fromJson(env.DETAILS_JSON).name }}.meta
        echo "DefaultImporter:" >> ${{ fromJson(env.DETAILS_JSON).name }}.meta
        echo "  externalObjects: {}" >> ${{ fromJson(env.DETAILS_JSON).name }}.meta
        echo "  userData:" >> ${{ fromJson(env.DETAILS_JSON).name }}.meta
        echo "  assetBundleName:" >> ${{ fromJson(env.DETAILS_JSON).name }}.meta
        echo "  assetBundleVariant:" >> ${{ fromJson(env.DETAILS_JSON).name }}.meta
        
    - name: Create GlitchSDK Directory
      run: |
        mkdir -p GlitchSDK
        
        # Copy assets to GlitchSDK
        cp -R ${{ fromJson(env.DETAILS_JSON).name }} GlitchSDK/
        echo "${{ fromJson(env.DETAILS_JSON).name }} copied to GlitchSDK."
        
    - name: Create Assets Directory
      run: |
        mkdir -p Assets
        
        # Copy GlitchSDK to Assets
        cp -R GlitchSDK Assets/
        echo "GlitchSDK copied to Assets."

        # Create .meta files for GlitchSDK
        touch Assets/GlitchSDK.meta
        echo "fileFormatVersion: 2" > Assets/GlitchSDK.meta
        echo "guid: 35413811acd778c49a42dd3a6f867699" >> Assets/GlitchSDK.meta
        echo "folderAsset: yes" >> Assets/GlitchSDK.meta
        echo "DefaultImporter:" >> Assets/GlitchSDK.meta
        echo "  externalObjects: {}" >> Assets/GlitchSDK.meta
        echo "  userData:" >> Assets/GlitchSDK.meta
        echo "  assetBundleName:" >> Assets/GlitchSDK.meta
        echo "  assetBundleVariant:" >> Assets/GlitchSDK.meta
    
    - run: |
        echo "Assets/GlitchSDK.meta" > metaList
        find Assets/GlitchSDK/ -name \*.meta >> metaList
    
    - run: mkdir a

    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'a/${{ fromJson(env.DETAILS_JSON).name }}.unitypackage'
        include-files: metaList
    - uses: actions/upload-artifact@master
      with:
        path: a
        name: package

    - name: Compare Tag Name and Details version
      run: |
        if [ "${{ github.ref }}" != "refs/tags/${{ fromJson(env.DETAILS_JSON).version }}" ];
        then
          echo "Tag name and Details version does not match. Skipping release creation."
          exit 0  # Exit with success to stop further steps
        fi
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ fromJson(env.DETAILS_JSON).version }}
        release_name: v${{ fromJson(env.DETAILS_JSON).version }}
        body: >
          ${{ join(' ', fromJson(env.DETAILS_JSON).releaseNotes) }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: 'a/${{ fromJson(env.DETAILS_JSON).name }}.unitypackage'
        asset_name: ${{ fromJson(env.DETAILS_JSON).name }}.unitypackage
        asset_content_type: application/octet-stream
