name: Build UnityPackage

on:
  push:
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "Runtime.meta" > metaList
        find Runtime/ -name \*.meta >> metaList
        
    - name: Prepare UnityPackage directory
      run: mkdir -p Assets/YourParentFolder/

    - name: Copy assets to UnityPackage directory
      run: cp -R Runtime/* Assets/YourParentFolder/
    
    - run: mkdir a

    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'a/output.unitypackage'
        include-files: metaList
    - uses: actions/upload-artifact@master
      with:
        path: a
        name: package