name: Build UnityPackage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Unity
      uses: game-ci/setup-unity@v1
      with:
        unityVersion: 2020.3.17f1
        modules: 'all'

    - name: Build UnityPackage
      run: |
        mkdir -p GlitchSDK
        # Copy your assets to the desired parent folder
        cp -R Editor/* GlitchSDK/

        # Build the UnityPackage
        unity -quit -batchmode -logFile -projectPath $(pwd) -exportPackage "GlitchSDK" "YourPackage.unitypackage"

    - name: Upload UnityPackage
      uses: actions/upload-artifact@v2
      with:
        name: YourPackage
        path: YourPackage.unitypackage
